### ISSUE TITLE
Determining FST based on winSFS output 

### ISSUE THREAD

**Issue by chrishusted** [malthesr/winsfs#10]
Hi there,

Thank you for implementing a much faster SFS method!  I was just curious if you have suggestions for performing FST using the winSFS ouput.  Will it work with the angsd implementation?  

Best,
Chris

**Comment by chrishusted** [comment]
It appears as though the answer is that you need to remove the header, but you can run the ANGSD FST calculation after doing so.

**Comment by malthesr** [comment]
Hi Chris,

Sorry for the slow reply. 

I haven't used the Fst stuff in ANGSD for a while, so I'm not sure about the details, but as you say, the output format of winsfs is the same as the one used in ANGSD, except it adds a header with the dimensions. So if all you need is an estimate of the SFS, you should be good to go by just removing the header.

**Comment by chrishusted** [comment]
Apologies for taking so long to respond!  This worked and I greatly appreciate the support.
