### ISSUE TITLE
Option to resume aborted runs?

### ISSUE THREAD

**Issue by jamesfifer** [malthesr/winsfs#8]
Hi thanks so much for adding 4d capabilities!!!! I have been trying it out on the same dataset that I was using for 3d, it seems to be working fine although taking a very looong time as you warned. 
I recently did a 4d run with 16 threads and it took about three weeks (215:22:53:00 CPU) to get to 14 epochs, given it took 61 epochs for the 3d I am guessing I still have quite a bit of time before it will converge. Not sure how hard this would be, but any chance you could add a resume feature? We are limited to about a month of cluster time per job so a resume feature would be really helpful for us! :) 

Here was the info on the run in case you are interested:
DEBUG [init] Using 16 threads for reading
INFO  [init] Reading (intersecting) sites in input SAF files into memory
DEBUG [init] Found 216836 (intersecting) sites in SAF files with shape 73/65/55/133
DEBUG [init] Shuffling SAF sites
DEBUG [init] Using 500 blocks, the first 336 containing 434 sites and the remaining blocks containing 433 sites
DEBUG [init] Using window size of 100 blocks per window
DEBUG [init] Creating uniform initial SFS
DEBUG [stop] Stopping rule set to log-likelihood tolerance 0.0001 (default)

**Comment by malthesr** [comment]
Hi James,

Using the `--initial` flag, you can input the SFS resulting from your previous run to start the next. Due to the way windowing works, this doesn't exactly correspond to resuming the run, but for most purposes I think it should be close enough.

Let me know if that doesn't address your problem.

**Comment by jamesfifer** [comment]
Oh I see ok great thanks! I was getting an error but was just because I was forgetting to add the shape header to the sfs file

**Comment by jamesfifer** [comment]
FYI took about 2 months total running 20 threads, but it worked in 30 epochs!!
